name: execute-report-junit
on:
  push:
    branches: [ main ]

jobs:
  postgres-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      #    steps:
      #      - name: install-postgres-client
      #        run: |
      #          apt-get update
      #          apt-get install --yes --no-install-recommends postgresql-client
      #
      #      - name: create-database-demo
      #        run: |
      #          psql -h postgres -U postgres -c 'CREATE DATABASE demo'
      #          psql -h postgres -U postgres -c 'SELECT datname FROM pg_database WHERE datistemplate = false'
      
