version: "3.9"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - ./env/postgres-image.env
    networks:
      - app_network

  application:
    restart: always
    build:
      context: ../
      dockerfile: java-dockerfile.yml
    ports:
      - "8080:8080"
    environment:
      - ./env/java-image.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge