version: "3.9"

services:
  database:
    image: postgres
    ports:
      - "3000:5432"
#    restart: always
#    env_file:
#      - ./env/postgres-image.env
    networks:
      - app_network

  backend:
#    restart: always
    build:
      context: ../back-end
#      dockerfile: Dockerfile
    image: ghcr.io/n3w-us3r/tryingout_backend:latest
    ports:
      - "8080:8080"
#    env_file:
#      - ./env/backend-dockerfile.env
    networks:
      - app_network

  admin-frontend:
    build:
      context: ../front-end/admin
    image: ghcr.io/n3w-us3r/tryingout_admin-frontend:latest
    ports:
      - "5000:3000"
    networks:
      - app_network

  user-frontend:
    build:
      context: ../front-end/user/
    image: ghcr.io/n3w-us3r/tryingout_user-frontend:latest
    ports:
      - "5050:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge