name: Java CI with Maven

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: create database demo
        run: |
          psql -h localhost -U ${{secrets.POSTGRES_USER}} -c 'CREATE DATABASE "demo";'
        env:
          PGPASSWORD: ${{secrets.POSTGRES_PASSWORD}}

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: run tests with maven
        run: |
          pwd
          cd back-end
          mvn test
        env:
          SPRING_DATASOURCE_URL: ${{secrets.SPRING_DATASOURCE_URL}}
          SPRING_DATASOURCE_USERNAME: ${{secrets.POSTGRES_USER}}
          SPRING_DATASOURCE_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}

      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "back-end/target/surefire-reports/*.xml"
