name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: install postgres client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: create database demo
        run: |
          psql -h localhost -U ${{secrets.POSTGRES_USER}} -c 'CREATE DATABASE "demo";'
        env:
          PGPASSWORD: ${{secrets.POSTGRES_PASSWORD}}

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: run tests with maven
        run: |
          pwd
          cd backend
          mvn -B package --file pom.xml
        env:
          spring.datasource.url: ${{secrets.SPRING_DATASOURCE_URL}}
          spring.datasource.username: ${{secrets.POSTGRES_USER}}
          spring.datasource.password: ${{secrets.POSTGRES_PASSWORD}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
