name: execute-report-junit
on:
  push:
    branches: [main]

jobs:
  postgres-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: install postgres client
      run: |
        apt-get update
        apt-get install --yes postgresql-client

      - name: create database demo
      run: |
        psql -h postgres -U postgres -c 'CREATE DATABASE "postgres_db";'
      env:
        POSTGRES_PASSWORD: postgres

